exports.SLUG_TO_TYPE = {
    'tien-hiep': 'Tiên Hiệp',
    'kiem-hiep': 'Kiếm Hiệp',
    'ngon-tinh': 'Ngôn Tình',
    'dam-my': 'Đam Mỹ',
    'quan-truong': 'Quan Trường',
    'vong-du': 'Võng Du',
    'khoa-huyen': 'Khoa Huyễn',
    'he-thong': 'Hệ Thống',
    'huyen-huyen': 'Huyền Huyễn',
    'di-gioi': 'Dị Giới',
    'di-nang': 'Dị Năng',
    'sac': 'Sắc',
    'quan-su': 'Quân Sự',
    'lich-su': 'Lịch Sử',
    'xuyen-khong': 'Xuyên Không',
    'xuyen-nhanh': 'Xuyên Nhanh',
    'trong-sinh': 'Trọng Sinh',
    'trinh-tham': 'Trinh Thám',
    'tham-hiem': 'Thám Hiểm',
    'linh-di': 'Linh Dị',
    'nguoc': 'Ngược',
    'sung': 'Sủng',
    'cung-dau': 'Cung Đấu',
    'nu-cuong': 'Nữ Cường',
    'gia-dau': 'Gia Đấu',
    'dong-phuong': 'Đông Phương',
    'do-thi': 'Đô Thị',
    'bach-hop': 'Bách Hợp',
    'hai-huoc': 'Hài Hước',
    'dien-van': 'Điền Văn',
    'co-dai': 'Cổ Đại',
    'mat-the': 'Mạt Thế',
    'truyen-teen': 'Truyện Teen',
    'phuong-tay': 'Phương Tây',
    'nu-phu': 'Nữ Phụ',
    'Light Novel': 'Light Novel',
    'viet-nam': 'Việt Nam',
    'doan-van': 'Đoản Văn',
    'review-sach': 'Review sách',
    'khac': 'Khác',
};
